---
- name: Start PostgreSQL for Odoo
  docker_container:
    name: db
    image: postgres:15
    env:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
  state: started

- name: Start Odoo
  docker_container:
    name: odoo
    image: odoo
    links:
      - "db:db"
  ports:
    - "8069:8069"
  state: started
